class Constants:
    ROOT_DIRECTORY = "E:\DoAn"

    DATASETS_DIRECTORY_INPUT = "E:\\DoAn\\DataSet\\Dan_D17CNTT\\data\\INPUT\\"
    DATASETS_DIRECTORY_OUT = "E:\\DoAn\\DataSet\\Dan_D17CNTT\\data\\KQ\\"

    DATASET_USER = DATASETS_DIRECTORY_INPUT + "tbluser.csv"
    DATASET_HOTEL = DATASETS_DIRECTORY_INPUT + "tblhotel.csv"
    DATASET_RATING = DATASETS_DIRECTORY_INPUT + "tblrate.csv"
    DATASET_MANH1 = DATASETS_DIRECTORY_INPUT + "manh1.csv"
    DATASET_MANH2 = DATASETS_DIRECTORY_INPUT + "manh2.csv"
    DATASET_MANH3 = DATASETS_DIRECTORY_INPUT + "manh3.csv"
    DATASET_MANH4 = DATASETS_DIRECTORY_INPUT + "manh4.csv"
    DATASET_MANH5 = DATASETS_DIRECTORY_INPUT + "manh5.csv"
    DATASET_MANH6 = DATASETS_DIRECTORY_INPUT + "manh6.csv"
    DATASET_MANH7 = DATASETS_DIRECTORY_INPUT + "manh7.csv"
    DATASET_MANH8 = DATASETS_DIRECTORY_INPUT + "manh8.csv"
